/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jriehn' at '14/10/14 14:13' with Gradle 1.12
 *
 * @author jriehn, @date 14/10/14 14:13
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
