import org.junit.Test;

import javax.jmdns.JmDNS;
import javax.jmdns.ServiceInfo;

import java.io.IOException;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jriehn' at '14/10/14 14:13' with Gradle 1.12
 *
 * @author jriehn, @date 14/10/14 14:13
 */
public class BonjourTest {

    final static String DEFAULT_DOMAIN="local.";
    final static String SERVICE_TYPE="_http._tcp."+DEFAULT_DOMAIN;

    @Test public void testSomeLibraryMethod() throws IOException {
        JmDNS jmdns = JmDNS.create();
        jmdns.addServiceListener(SERVICE_TYPE, new SimplePrintListener());

        ServiceInfo[] serviceInfoList = jmdns.list(SERVICE_TYPE);
        System.out.println("List "+SERVICE_TYPE);
        for (int i = 0; i < serviceInfoList.length; i++) {
            System.out.println(serviceInfoList[i].toString());
        }
    }
}
